androidx.datastore.core.Final
<androidx.datastore.core.Final: java.lang.Throwable finalException>
    public void <init>(java.lang.Throwable)
    {
        androidx.datastore.core.Final r0;
        java.lang.Throwable r1;

        r0 := @this: androidx.datastore.core.Final;

        r1 := @parameter0: java.lang.Throwable;

        staticinvoke <kotlin.jvm.internal.Intrinsics: void checkNotNullParameter(java.lang.Object,java.lang.String)>(r1, "finalException");

        specialinvoke r0.<androidx.datastore.core.State: void <init>(kotlin.jvm.internal.DefaultConstructorMarker)>(null);

        r0.<androidx.datastore.core.Final: java.lang.Throwable finalException> = r1;

        return;
    }

    public final java.lang.Throwable getFinalException()
    {
        androidx.datastore.core.Final r0;
        java.lang.Throwable $r1;

        r0 := @this: androidx.datastore.core.Final;

        $r1 = r0.<androidx.datastore.core.Final: java.lang.Throwable finalException>;

        return $r1;
    }

