androidx.compose.ui.test.junit4.UncaughtExceptionHandler
<androidx.compose.ui.test.junit4.UncaughtExceptionHandler: java.lang.Throwable exception>
    public void <init>()
    {
        androidx.compose.ui.test.junit4.UncaughtExceptionHandler r0;
        kotlinx.coroutines.CoroutineExceptionHandler$Key $r1;
        kotlin.coroutines.CoroutineContext$Key $r2;

        r0 := @this: androidx.compose.ui.test.junit4.UncaughtExceptionHandler;

        $r1 = <kotlinx.coroutines.CoroutineExceptionHandler: kotlinx.coroutines.CoroutineExceptionHandler$Key Key>;

        $r2 = (kotlin.coroutines.CoroutineContext$Key) $r1;

        specialinvoke r0.<kotlin.coroutines.AbstractCoroutineContextElement: void <init>(kotlin.coroutines.CoroutineContext$Key)>($r2);

        return;
    }

    public void handleException(kotlin.coroutines.CoroutineContext, java.lang.Throwable)
    {
        androidx.compose.ui.test.junit4.UncaughtExceptionHandler r0, r3;
        kotlin.coroutines.CoroutineContext r1;
        java.lang.Throwable r2, $r4, $r5, $r6;
        kotlin.Unit $r7;

        r0 := @this: androidx.compose.ui.test.junit4.UncaughtExceptionHandler;

        r1 := @parameter0: kotlin.coroutines.CoroutineContext;

        r2 := @parameter1: java.lang.Throwable;

        staticinvoke <kotlin.jvm.internal.Intrinsics: void checkNotNullParameter(java.lang.Object,java.lang.String)>(r1, "context");

        staticinvoke <kotlin.jvm.internal.Intrinsics: void checkNotNullParameter(java.lang.Object,java.lang.String)>(r2, "exception");

        r3 = r0;

        entermonitor r3;

     label1:
        $r4 = r0.<androidx.compose.ui.test.junit4.UncaughtExceptionHandler: java.lang.Throwable exception>;

        if $r4 != null goto label2;

        r0.<androidx.compose.ui.test.junit4.UncaughtExceptionHandler: java.lang.Throwable exception> = r2;

        goto label3;

     label2:
        $r5 = r0.<androidx.compose.ui.test.junit4.UncaughtExceptionHandler: java.lang.Throwable exception>;

        staticinvoke <kotlin.jvm.internal.Intrinsics: void checkNotNull(java.lang.Object)>($r5);

        staticinvoke <kotlin.ExceptionsKt: void addSuppressed(java.lang.Throwable,java.lang.Throwable)>($r5, r2);

     label3:
        $r7 = <kotlin.Unit: kotlin.Unit INSTANCE>;

     label4:
        exitmonitor r3;

        goto label7;

     label5:
        $r6 := @caughtexception;

     label6:
        exitmonitor r3;

        throw $r6;

     label7:
        return;

        catch java.lang.Throwable from label1 to label4 with label5;
        catch java.lang.Throwable from label5 to label6 with label5;
    }

    public final void throwUncaught()
    {
        androidx.compose.ui.test.junit4.UncaughtExceptionHandler r0, r1;
        java.lang.Throwable r2, $r3;
        kotlin.Unit $r4;

        r0 := @this: androidx.compose.ui.test.junit4.UncaughtExceptionHandler;

        r1 = r0;

        entermonitor r1;

     label1:
        r2 = r0.<androidx.compose.ui.test.junit4.UncaughtExceptionHandler: java.lang.Throwable exception>;

        if r2 == null goto label2;

        r0.<androidx.compose.ui.test.junit4.UncaughtExceptionHandler: java.lang.Throwable exception> = null;

        throw r2;

     label2:
        $r4 = <kotlin.Unit: kotlin.Unit INSTANCE>;

     label3:
        exitmonitor r1;

        goto label6;

     label4:
        $r3 := @caughtexception;

     label5:
        exitmonitor r1;

        throw $r3;

     label6:
        return;

        catch java.lang.Throwable from label1 to label3 with label4;
        catch java.lang.Throwable from label4 to label5 with label4;
    }

