kotlinx.coroutines.UndispatchedCoroutine
    protected void afterResume(java.lang.Object)
    {
        kotlinx.coroutines.UndispatchedCoroutine $r0;
        java.lang.Object $r1;
        java.lang.NullPointerException r2;

        $r0 := @this: kotlinx.coroutines.UndispatchedCoroutine;

        $r1 := @parameter0: java.lang.Object;

        r2 = new java.lang.NullPointerException;

        specialinvoke r2.<java.lang.NullPointerException: void <init>(java.lang.String)>("Null throw statement replaced by Soot");

        throw r2;
    }

    public final boolean clearThreadContext()
    {
        kotlinx.coroutines.UndispatchedCoroutine $r0;
        java.lang.NullPointerException r1;

        $r0 := @this: kotlinx.coroutines.UndispatchedCoroutine;

        r1 = new java.lang.NullPointerException;

        specialinvoke r1.<java.lang.NullPointerException: void <init>(java.lang.String)>("Null throw statement replaced by Soot");

        throw r1;
    }

    public final void saveThreadContext(kotlin.coroutines.CoroutineContext, java.lang.Object)
    {
        kotlinx.coroutines.UndispatchedCoroutine $r0;
        java.lang.Object $r1;
        kotlin.coroutines.CoroutineContext $r2;
        java.lang.NullPointerException r3;

        $r0 := @this: kotlinx.coroutines.UndispatchedCoroutine;

        $r2 := @parameter0: kotlin.coroutines.CoroutineContext;

        $r1 := @parameter1: java.lang.Object;

        r3 = new java.lang.NullPointerException;

        specialinvoke r3.<java.lang.NullPointerException: void <init>(java.lang.String)>("Null throw statement replaced by Soot");

        throw r3;
    }

